-- BEI Streamlit import storage.
-- Run this file once in Supabase SQL Editor.
-- The Streamlit app uses a server-only Supabase key; RLS stays enabled.

create extension if not exists pgcrypto;

create table if not exists public.bei_import_batches (
  id uuid primary key default gen_random_uuid(),
  trading_date date not null unique,
  uploaded_at timestamptz not null default now(),
  file_manifest jsonb not null default '{}'::jsonb,
  row_counts jsonb not null default '{}'::jsonb,
  status text not null default 'ready' check (status in ('ready', 'complete', 'error'))
);

create table if not exists public.bei_import_rows (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references public.bei_import_batches(id) on delete cascade,
  trading_date date not null,
  dataset_type text not null check (dataset_type in (
    'ringkasan_saham', 'ringkasan_broker', 'ringkasan_perdagangan', 'daftar_saham', 'ringkasan_indeks'
  )),
  row_number integer not null,
  ticker text not null default '',
  row_data jsonb not null,
  created_at timestamptz not null default now(),
  unique (batch_id, dataset_type, row_number)
);

create index if not exists bei_import_rows_date_idx
  on public.bei_import_rows (trading_date);
create index if not exists bei_import_rows_ticker_idx
  on public.bei_import_rows (ticker);
create index if not exists bei_import_rows_dataset_idx
  on public.bei_import_rows (dataset_type);

create table if not exists public.ai_analyses (
  id uuid primary key default gen_random_uuid(),
  ticker text not null,
  created_at timestamptz not null default now(),
  context jsonb not null,
  analysis jsonb not null
);

alter table public.bei_import_batches enable row level security;
alter table public.bei_import_rows enable row level security;
alter table public.ai_analyses enable row level security;

-- New Supabase projects may revoke automatic Data API grants. RLS remains
-- enabled, while the server-only service_role/secret key gets table access.
grant usage on schema public to service_role;
grant select, insert, update, delete on public.bei_import_batches to service_role;
grant select, insert, update, delete on public.bei_import_rows to service_role;
grant select, insert, update, delete on public.ai_analyses to service_role;
grant usage, select on sequence public.bei_import_rows_id_seq to service_role;

-- The server-side service-role key bypasses RLS. No public/anon policy is
-- created because BEI uploads and AI context should not be publicly readable.

insert into storage.buckets (id, name, public)
values ('saham', 'saham', false)
on conflict (id) do nothing;
